url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: UC3Music
email: uc3music@gmail.com
description: 
    Asociación universitaria. Música, cacharros y ruido, aunque no necesariamente en este orden.
baseurl: ""
url: "http://uc3music.github.io" 
twitter_username: UC3Music
github_username:  uc3music
mailing_list: https://t.me/UC3Music

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c22425
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/UC3Music
  - title: twitter
    url: http://twitter.com/UC3Music
  - title: facebook
    url: https://www.facebook.com/UC3Music
  - title: instagram 
    url: https://instagram.com/uc3music
  - title: envelope
    url : mailto:uc3music@gmail.com 
  - title: github
    url: http://github.com/UC3Music
  - title: linkedin
    url: https://www.linkedin.com/company/uc3music/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

